config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :flats
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      flash[:notice] = "Flat was Succesfully created."
      redirect_to @flat
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      flash[:notice] = "Flat was successfully updated."
      redirect_to @flat
    else
      render :new
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    flash[:notice] = "Falt was sucessfully deleted."
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<!-- app/views/flats/_form.html.erb -->
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests, label: "Number of guests" %>
  <%= f.input :price_per_night, label: "Price per night" %>
  <%= f.input :picture_url, label: "Picture URL" %> <!-- Champ pour l'URL de l'image -->
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<!-- app/views/flats/_form.html.erb -->
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
<!-- app/views/flats/edit.html.erb -->
<h1>Edit Flat</h1>
<%= render 'form' %>
<%= link_to 'Cancel', flat_path(@flat), class: "btn btn-secondary" %>
<!-- app/views/flats/new.html.erb et app/views/flats/edit.html.erb -->
<div class="container mt-4">
  <h1><%= @flat.new_record? ? 'Add a new Flat' : 'Edit Flat' %></h1>
  <%= render 'form' %>
  <%= link_to 'Cancel', flats_path, class: "btn btn-danger" %>
</div>

app/views/flats/index.html.erb
<!-- app/views/flats/index.html.erb -->
<h1>All our Flats (<%= @flats.count %>)</h1>

<div class="row">
  <% @flats.each do |flat| %>
    <div class="col-md-4 mb-4">
      <div class="card h-100">
        <!-- Image du flat -->
        <img src="<%= flat.picture_url %>" class="card-img-top" alt="<%= flat.name %>">
        <div class="card-body">
          <h5 class="card-title"><%= flat.name %></h5>
          <p class="card-text"><%= flat.address %></p>
          <p>
            <i class="fas fa-user"></i> <%= flat.number_of_guests %> guests
            <i class="fas fa-euro-sign"></i> <%= flat.price_per_night %> per night
          </p>
          <%= link_to 'More info', flat_path(flat), class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_flat_path(flat), class: "btn btn-warning mx-2" %>
          <%= link_to 'Remove', flat_path(flat), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'Add Flat', new_flat_path, class: "btn btn-primary mt-4" %>

app/views/flats/new.html.erb
<%# app/views/flats/new.html.erb et app/views/flats/edit.html.erb --> %>
<div class="container mt-4">
  <h1><%= @flat.new_record? ? 'Add a new Flat' : 'Edit Flat' %></h1>
  <%= render 'form' %>
  <%= link_to 'Cancel', flats_path, class: "btn btn-danger" %>
</div>

app/views/flats/show.html.erb
<!-- app/views/flats/show.html.erb -->
<div class="container mt-4">
  <!-- Titre du flat et adresse -->
  <h1><%= @flat.name %></h1>
  <p class="text-muted"><%= @flat.address %></p>

  <div class="row mt-4">
    <!-- Section de gauche : Image, Description, Détails -->
    <div class="col-md-8">
      <%# Image du flat (URL stockée dans l'attribut picture_url si disponible) %>
      <img src="<%= @flat.picture_url %>" class="img-fluid" alt="<%= @flat.name %>">

      <!-- Description du flat -->
      <div class="mt-4">
        <h2>A bit more about this flat...</h2>
        <p><%= @flat.description %></p>
      </div>

      <!-- Détails : nombre de personnes et prix par nuit -->
      <div class="mt-4">
        <h3>Details</h3>
        <p>
          <i class="fas fa-user"></i> <%= @flat.number_of_guests %> guests
          <i class="fas fa-euro-sign"></i> <%= @flat.price_per_night %> per night
        </p>
      </div>
    </div>

    <!-- Section de droite : formulaire de réservation et options de partage -->
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <h5>Book this place!</h5>
          <form>
            <div class="mb-3">
              <label for="from" class="form-label">From:</label>
              <input type="date" class="form-control" id="from">
            </div>
            <div class="mb-3">
              <label for="to" class="form-label">To:</label>
              <input type="date" class="form-control" id="to">
            </div>
            <button type="submit" class="btn btn-success w-100">Book</button>
          </form>
        </div>
      </div>

      <!-- Section de partage -->
      <h5 class="mt-4">Share</h5>
      <i class="fab fa-facebook fa-2x"></i>
      <i class="fab fa-twitter fa-2x"></i>
      <i class="fab fa-pinterest fa-2x"></i>
    </div>
  </div>

  <!-- Lien de retour à la liste des flats -->
  <%= link_to 'Back to all flats', flats_path, class: "btn btn-secondary mt-4" %>
</div>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Airbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>
  <body>
    <%= yield %>

    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>